;METADATA=(Diff=true, UseCommands=true)
[/Script/FortniteGame.FortGameUserSettings]
CosmeticStreamingEnabled=CodeSet_Enabled
FortniteReleaseVersion=14
UnlockConsoleFPS=False
SubGameSelectCount_Athena=2
SubGameLastSelectedTime_Athena=2026.05.16-21.54.24
SubGameSelectCount_Campaign=0
SubGameLastSelectedTime_Campaign=0001.01.01-00.00.00
LastTimeSettingsSnapshotUploaded=2026.05.16-19.54.25
LastTimeLockerPresetCountUploaded=2026.05.16-19.54.23
FirstLoginOnDevice=2026.05.16-21.54.20
SafeZone=1.000000
bIsSafeZoneSet=False
CachedPlayerLevel=0
bShowActorsWithSeasonItemTagMapIndicators=True
CachedBattleStars=0
CachedAlienStylePoints=0
CachedStylePoints=0
CachedClaimableRewards=()
CachedHighestBattlePassUnlockedPage=1
bShowCareerTabBang=False
bArmASREnabled=False
CustomVoiceChatInputDevice=
CustomVoiceChatOutputDevice=
CustomVoiceChatInputDeviceId=
CustomVoiceChatOutputDeviceId=
bMotionBlur=False
bAllowUIParallax=True
bShowGrass=False
bShowFPS=True
bUseGPUCrashDebugging=False
bStopRenderingInBackground=False
bLatencyTweak1=False
LatencyTweak2=0
bLatencyFlash=False
FortAntiAliasingMethod=Disabled
bEnableDLSSFrameGeneration=False
TemporalSuperResolutionQuality=Native
DLSSQuality=0
XeSSQuality=0
PotentiallyUpscaledResolutionQuality=100.000000
NeverUpscaledResolutionQuality=100.000000
bUseNanite=False
DesiredGlobalIlluminationQuality=0
DesiredReflectionQuality=0
PreNaniteGlobalIlluminationQuality=0
PreNaniteReflectionQuality=0
bRayTracing=False
b120FpsMode=False
FrontendFrameRateLimit=120
bIsEnergySavingEnabledIdle=False
bIsEnergySavingEnabledFocusLoss=False
EnergySavingLevelFocusLoss=1
DisplayGamma=2.700000
UserInterfaceContrast=1.000000
NamedTimes=()
NamedCounts=(("lastfrontendflow_Fortnite", 40),("lastfrontendflow_Fortnite_HotfixVer", 0),("UEnableMultiFactorModal::ShouldShowMFASplashScreen", 40),("UEnableMultiFactorModal::ShouldShowMFASplashScreen_HotfixVer", 0))
BattlePassOverrideTracker=0
NewestProgressiveCosmeticSetSeen=
CurrentLockerSortsByTag=()
ArchetypeShuffleSelectionBias=()
bLockerHideUnsupportedItems=False
bLockerSortItemsByRelevance=True
bHasUsedBattlePassCrewUpsellNavButton=True
LastExpectedShopRefreshTime=0001.01.01-00.00.00
bHasSeenItemShop=True
AboutShopModalVersionSeen=0
bHasSeenJunoOutfitsFTUE=True
JunoFTUEQuestTrackingDisabledVersion=0
bHasSeenDonutShopSequence=True
DonutIdleGameHighScore=0.000000
RowIdToOfferSeenLevel=()
LastSelectedIsland="{\"LinkId\":\"playlist_defaultsolo\",\"Session\":{\"iD\":\"\",\"joinInfo\":{\"joinability\":\"CanNotBeJoinedOrWatched\",\"sessionKey\":\"\"}},\"MatchmakingSettingsV2\":{\"/Fortnite.com/Matchmaking:Region\":\"NONE\"}}"
LastPlayedIsland="{\"LinkId\":\"5492-6089-6665\",\"Session\":{\"iD\":\"\",\"joinInfo\":{\"joinability\":\"CanNotBeJoinedOrWatched\",\"sessionKey\":\"\"}},\"MatchmakingSettingsV1\":{\"world\":{\"iD\":\"\",\"ownerId\":\"INVALID\",\"name\":\"\",\"bIsJoinable\":false},\"productModes\":[],\"privacy\":\"Private\",\"regionId\":\"EU\"}}"
LastSelectedPlaylist=(PlaylistName="NoPlaylist",TournamentID="",EventWindowId="",LinkId=(Mnemonic="playlist_defaultsolo",Version=-1),ProductModes=)
LastSelectedFillOption=True
bLastSelectedPrivateMatchOption=True
CustomMatchOptions=()
CreativeOptions=()
bHasSeenCreativePhoneTutorial=True
bHasSeenCreativeHeatmapTutorial=True
CreativeOptionLastUsedCategory=0
CreativeOptionLastUsedIndexInCategory=0
LastSelectedChildActivityMap=()
ClamOneDMVersion=1
ClamOneDMPreviousVersion=1
ClamOneDMMaxEvents=200
LastNewsVersionViewedBR=
LastNewsVersionViewedCreative=
LastNewsVersionViewedSTW=
LastPRMEtag=
LastFrontEndBackPlateStageUsed[0]=season4040
LastFrontEndBackPlateStageUsed[1]=default
bEulaAccepted=True
EulaAcceptedUserId=078cfc9474814dc38469c5570e68e4c4
LastEulaCheckTime=2026.05.16-19.54.22
HUDLayoutData[0]=(LayoutEntries=)
HUDLayoutData[1]=(LayoutEntries=)
HUDLayoutData[2]=(LayoutEntries=)
bHasBeenNotifiedAboutLegacyLayoutDeprecation=False
ActiveHUDProfileIdentifier=(HUDProfileType=(TagName=""),Guid=00000000000000000000000000000000)
bTimesSeenBacchusLoadTutorial=0
bHasSeenTapToShoot=False
NumTimesSeeingPanningTip=0
FireModeData=(bAutoFireIsEnabled=True,b3DTouchEnabled=False,bTapToShootEnabled=False,bAlwaysShowDedicatedButton=True,FireModeType=Unset)
SimpleMobileStats=(GamesPlayed=0,SecondsPlayed=0,KillCount=0,BestResult=100,LastReviewPromptDay=0001.01.01-00.00.00,CampaignGamesPlayed=0)
SelectedAndroidAppStore=Unset
AudioOutputDeviceId=
bUseHeadphoneMode=False
InitialBenchmarkState=1
bDisableMouseAcceleration=False
ChosenLoginType=None
SocialImportOptedOutVersion=0
VKImportOptedOutVersion=0
bHasSeenErebusSocialImport=True
bHasSeenFriendImportToast=True
LastSocialImportPromptTime=0001.01.01-00.00.00
bAutoImportFriendEnabled=True
bSeenLetoSellModal=True
SocialImportPromptCountCurrentVersion=0
SocialImportPromptCountAllVersions=0
VKImportPromptCountCurrentVersion=0
VKImportPromptCountAllVersions=0
LastAccountItemWarningTime=0001.01.01-00.00.00
bMultiFactorAuthModalOpOut=False
LastEnableMFAModalPromptTime=0001.01.01-00.00.00
LastVKImportPromptTime=0001.01.01-00.00.00
LastAffiliateToastTime=0001.01.01-00.00.00
FailedInviteMap=()
MobileRecommendationDismissedVersion=0
ShowLiveStreamPictureInPictureInMatchV2=Default
CurrentLivePiPStreamOverrideCounter=0
SelectedFrontEnd=
bNeverShowMobileLink=True
bHasMigratedDownloadSettings=False
bSendAppsFlyerEventOnInstallation=True
bAllowFullGameDownload=False
ReducedDataUsage=UnSet
bAllowCellularDownload=False
LastAutoDownloadHighResTextureReminder=639145582856660000
bOverrideMobileScalabilityForNewUser=False
bShouldTryShowMobileDefaultSettingsChanged=False
bAutoLaunchFullGame=False
bAllowDownloadHighResMips=False
ContentQualityLevelSelected=Unset
bAllowLowPowerMode=False
bAllowVideoPlayback=True
MobileFPSMode=Mode_30Fps
MobileQualitySettingsResetDefaultsGUID=
bHasSeenSamsungPressureSensorWarning=False
bNeverDisplaySamsungPressureSensorWarning=False
bHasRecentlySeenBadMatchPopup=False
MatchesSinceLastBadMatchPopup=0
bHasAlreadyRatedOnGooglePlay=False
DaysToSnoozeBeforeNextGooglePlayRating=0
GooglePlayRatingDelayedOccurences=0
ParsleyIdleTime=Never
bShowTemperature=False
LastGameStartNotificationSentTime=
LastYearForcedDisplayWinterfestInfoButton=0
LastYearWinterfestWasSeen=0
bHasSeenSidekickWelcomePopup=True
bHasSeenLobbyModeSetNotification=True
bHasSeenLobbyModeChangedNotification=False
bHasSeenDiscoveryDetailsModeSetNotification=True
bHasSeenDiscoveryCCUModal=True
bHasSeenCreatorPageFirstTimeTooltip=True
LowInputLatencyModeIsEnabled=True
bNeedsToSeeFireModeSelectionReminder=False
MatchesSinceInitialFireModeSelection=0
LastLaunchPushNotificationState=NotSet
bIsPushNotificationConsentValid=False
bUseVSync=False
bUseDynamicResolution=False
ResolutionSizeX=1920
ResolutionSizeY=1080
LastUserConfirmedResolutionSizeX=1920
LastUserConfirmedResolutionSizeY=1080
LastConfirmedFullscreenMode=1
PreferredFullscreenMode=1
AudioQualityLevel=1
LastConfirmedAudioQualityLevel=1
FrameRateLimit=0.000000
DesiredScreenWidth=1920
DesiredScreenHeight=1080
LastUserConfirmedDesiredScreenWidth=1920
LastUserConfirmedDesiredScreenHeight=1080
LastRecommendedScreenWidth=-1.000000
LastRecommendedScreenHeight=-1.000000
LastCPUBenchmarkResult=-1.000000
LastGPUBenchmarkResult=-1.000000
LastGPUBenchmarkMultiplier=1.000000
bUseHDRDisplayOutput=False
HDRDisplayOutputNits=1000
bShowCareerShowcaseTabBang=True
ArmASRQuality=1
QualcommGSRQuality=1
CurrentLockerFiltersByTag=()
HasSeenAboutItemModalTypes=()
EulaCacheVersion=1
TextureQualityLevel=UnSet
GlobalConfigData=()
DisplayID=
DisplayIndex=-1
LastUserConfirmedDisplayID=
LastUserConfirmedDisplayIndex=-1
DynamicResolutionFrameTarget=0.000000
RecentSelections="(Island={\"LinkId\":\"5492-6089-6665\",\"Session\":{\"iD\":\"\",\"joinInfo\":{\"joinability\":\"CanNotBeJoinedOrWatched\",\"sessionKey\":\"\"}},\"MatchmakingSettingsV1\":{\"world\":{\"iD\":\"\",\"ownerId\":\"INVALID\",\"name\":\"\",\"bIsJoinable\":false},\"productModes\":[],\"privacy\":\"Private\",\"regionId\":\"EU\"}},Timestamp=1778961486,bUsingGracefulUpgrade=True,MatchmakingId=\"3F8AC4AF4EC5B2F53548AEBD51B1DB04\")"
RecentSelections="(Island={\"LinkId\":\"experience_br\",\"Session\":{\"iD\":\"\",\"joinInfo\":{\"joinability\":\"CanNotBeJoinedOrWatched\",\"sessionKey\":\"\"}},\"MatchmakingSettingsV2\":{\"/Fortnite.com/Matchmaking:SquadFill\":\"NoFill\",\"/Fortnite.com/Matchmaking:Ranked\":\"Unranked\",\"/Fortnite.com/BattleRoyale/Matchmaking:TeamSize\":\"Solo\",\"/Fortnite.com/BattleRoyale/Matchmaking:BuildMode\":\"Build\",\"/Fortnite.com/Matchmaking:Region\":\"EU\"}},Timestamp=1778961267,bUsingGracefulUpgrade=True,MatchmakingId=\"A2B064F94D34152361D13F8EA543FDB6\")"

[ScalabilityGroups]
sg.ResolutionQuality=100
sg.ViewDistanceQuality=0
sg.AntiAliasingQuality=0
sg.ShadowQuality=0
sg.GlobalIlluminationQuality=0
sg.ReflectionQuality=0
sg.PostProcessQuality=0
sg.TextureQuality=0
sg.EffectsQuality=0
sg.FoliageQuality=0
sg.ShadingQuality=0
sg.LandscapeQuality=0

[/Script/FortniteUIAudio.FortAudioUserMixSubsystem]
UserMixCurrentValues=(BusName="CB_Slider_Main",Volume=0.800000)
UserMixCurrentValues=(BusName="CB_Slider_Chat",Volume=1.000000)
UserMixCurrentValues=(BusName="CB_Slider_Cinematics",Volume=0.000000)
UserMixCurrentValues=(BusName="CB_Slider_Dialogue",Volume=0.000000)
UserMixCurrentValues=(BusName="CB_Slider_Music",Volume=0.050000)
UserMixCurrentValues=(BusName="CB_Slider_PIP",Volume=0.000000)
UserMixCurrentValues=(BusName="CB_Slider_SFX",Volume=0.800000)
UserMixCurrentValues=(BusName="CB_IsInFrontend",Volume=1.000000)
UserMixCurrentValues=(BusName="CB_Slider_LobbyMusic",Volume=1.000000)

[ChatSettings]
HideSocialName=False
AutoImportFriends=False
ShowNotifications=True
NeverFadeMessages=False
ShowTimeStamps=False
ShowWhispersInAllTabs=False
ShowCustomTab=False
ShowWhispersTab=False
ShowGlobalTab=True
ShowCombatAndEventsTab=True
ShowClanTabs=True
HideOffline=False
HideOutgoing=False
HideSuggestions=False
HideRecent=False
HideBlocked=True
FilterMatureLanguage=False
DisplayCharacterNames=False
FriendInviteReceivedCueEnabled=False
GameOrPartyInviteReceivedCueEnabled=False
MessageReceivedCueEnabled=False
SoundEnabled=False
ShowTextChat=True
FontSize=1
WindowHeight=0
WindowOpacity=0.5

[D3DRHIPreference]
PreferredRHI=dx12
PreferredFeatureLevel=es31

